import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.ensemble import IsolationForest
from fpdf import FPDF
import hashlib
import time
import sqlite3
import os

# --- 1. CONFIGURAZIONE SISTEMA ---
st.set_page_config(
    page_title="Insight Certifier | Enterprise AI",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. GESTIONE PASSWORD & AMBIENTE ---
def check_password():
    """Ritorna True se l'utente ha la password corretta."""
    if "password_correct" not in st.session_state:
        st.text_input("🔒 Accesso Riservato. Inserisci la Security Key:", type="password", key="password_input", on_change=password_entered)
        return False
    return st.session_state["password_correct"]

def password_entered():
    if st.session_state["password_input"] == st.secrets["password"]:
        st.session_state["password_correct"] = True
        del st.session_state["password_input"]
    else:
        st.session_state["password_correct"] = False
        st.error("⛔ Accesso Negato.")

if not check_password():
    st.stop()

# --- RILEVAMENTO AMBIENTE ---
try:
    APP_MODE = st.secrets["app_mode"]
except:
    APP_MODE = "cloud" # Default

# --- 0. CONFIGURAZIONE UTENTE ---
USER_NAME = "Francesco Pagliara"
ROLE = "Head of Data Strategy"
DB_NAME = "insight_certifier_memory.db"

# --- CSS CUSTOM ---
st.markdown("""
<style>
    .stTabs [data-baseweb="tab-list"] { gap: 10px; }
    .stTabs [data-baseweb="tab"] { height: 50px; border-radius: 4px 4px 0px 0px; }
    .footer {
        position: fixed; left: 0; bottom: 0; width: 100%;
        background-color: #0e1117; color: #808495;
        text-align: center; padding: 10px; font-size: 12px;
        border-top: 1px solid #262730; z-index: 100;
    }
    .block-container { padding-bottom: 50px; }
</style>
""", unsafe_allow_html=True)

# --- GESTIONE DATABASE ---
def init_db():
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            filename TEXT,
            total_rows INTEGER,
            anomalies_found INTEGER,
            risk_value REAL,
            user TEXT,
            hash_signature TEXT
        )
    ''')
    conn.commit()
    conn.close()

def save_audit_log(filename, total_rows, anomalies_count, risk_val, signature):
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    c.execute('''
        INSERT INTO audit_log (timestamp, filename, total_rows, anomalies_found, risk_value, user, hash_signature)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', (timestamp, filename, total_rows, anomalies_count, risk_val, USER_NAME, signature))
    conn.commit()
    conn.close()

def load_history():
    try:
        conn = sqlite3.connect(DB_NAME)
        df = pd.read_sql_query("SELECT * FROM audit_log ORDER BY id DESC", conn)
        conn.close()
        return df
    except:
        return pd.DataFrame()

init_db()

# --- INIZIALIZZAZIONE SESSION STATE ---
if 'audit_done' not in st.session_state: st.session_state.audit_done = False
if 'df_full' not in st.session_state: st.session_state.df_full = None
if 'df_anomalies' not in st.session_state: st.session_state.df_anomalies = pd.DataFrame()
if 'risk_val' not in st.session_state: st.session_state.risk_val = 0.0
if 'total_rows' not in st.session_state: st.session_state.total_rows = 0
if 'target_col' not in st.session_state: st.session_state.target_col = ""
if 'contamination' not in st.session_state: st.session_state.contamination = 0.05

# --- MOTORE PDF ---
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(30, 60, 100)
        self.cell(0, 10, 'INSIGHT CERTIFIER - ENTERPRISE AUDIT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Decision Integrity Assurance Protocol', 0, 1, 'C')
        self.ln(10)
        self.line(10, 30, 200, 30)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Confidential - Generated by {USER_NAME} - Page {self.page_no()}/{{nb}}', 0, 0, 'C')

def generate_pdf(df_anomalies, total_rows, risk_value, target_col_name):
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, f'Date of Issue: {time.strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'R')
    pdf.ln(5)
    
    # 1. EXECUTIVE SUMMARY
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(230, 230, 250)
    pdf.cell(0, 10, "  1. EXECUTIVE SUMMARY", 0, 1, 'L', 1)
    pdf.ln(5)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f"Total Transactions Audited: {total_rows}", 0, 1)
    pdf.set_text_color(200, 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 8, f"Critical Anomalies Detected: {len(df_anomalies)}", 0, 1)
    pdf.cell(0, 8, f"Total Financial Exposure: EUR {risk_value:,.2f}", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # 2. FORENSIC DETAIL
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(230, 230, 250)
    pdf.cell(0, 10, "  2. FORENSIC DETAIL (TOP PRIORITY)", 0, 1, 'L', 1)
    pdf.ln(5)
    pdf.set_font('Courier', 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(30, 8, 'ID REF', 1, 0, 'C', 1)
    pdf.cell(50, 8, 'DEPARTMENT', 1, 0, 'C', 1)
    pdf.cell(50, 8, 'VALUE (EUR)', 1, 0, 'C', 1)
    pdf.cell(60, 8, 'AI VERDICT', 1, 1, 'C', 1)
    pdf.set_font('Courier', '', 10)
    for index, row in df_anomalies.iterrows():
        id_ord = str(row.iloc[0])[:10]
        reparto = str(row['Reparto'])[:18] if 'Reparto' in row else "N/A"
        importo = row[target_col_name]
        pdf.cell(30, 8, id_ord, 1)
        pdf.cell(50, 8, reparto, 1)
        pdf.cell(50, 8, f"{importo:,.2f}", 1)
        pdf.set_text_color(200, 0, 0)
        pdf.cell(60, 8, 'CRITICAL OUTLIER', 1, 1, 'C')
        pdf.set_text_color(0, 0, 0)
    pdf.ln(15)

    # 3. HASH
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 10, "  3. BLOCKCHAIN-READY INTEGRITY HASH", 0, 1, 'L', 1)
    pdf.ln(5)
    data_bytes = str(df_anomalies.values).encode()
    digital_signature = hashlib.sha256(data_bytes).hexdigest()
    pdf.set_font('Arial', '', 9)
    pdf.multi_cell(0, 5, "This document is digitally secured using SHA-256 hashing algorithms.")
    pdf.ln(5)
    pdf.set_font('Courier', 'B', 8)
    pdf.multi_cell(0, 5, f"SECURE HASH: {digital_signature}")
    filename = "Insight_Enterprise_Audit.pdf"
    pdf.output(filename)
    return filename, digital_signature

# --- SIDEBAR DINAMICA ---
with st.sidebar:
    st.title("🛡️ Insight Certifier")
    if APP_MODE == "local":
        st.caption("Enterprise Edition (Local)")
    else:
        st.caption("Cloud Secure Demo")
    
    st.divider()
    st.write("### 👤 User Profile")
    st.info(f"**{USER_NAME}**")
    st.caption(ROLE)
    st.write("### 📡 System Status")
    st.success("AI Core: **ONLINE**")
    
    if APP_MODE == "local":
        st.success("Database: **PERSISTENT** 💾")
    else:
        st.warning("Database: **EPHEMERAL** ☁️")
        
    st.divider()
    if st.button("🔒 Logout / Lock"):
        del st.session_state["password_correct"]
        st.rerun()

# --- MAIN ---
st.title("🛡️ Insight Certifier Platform")
st.markdown("##### The Ultimate Decision Assurance System")

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "🏠 Control Room", "🕵️‍♂️ Audit Operations", "📜 Storico Log", "⚙️ Advanced Lab", "🎓 Academy"
])

# --- TAB 1 ---
with tab1:
    st.subheader("Global Security Overview")
    st.write(f"### 👋 Benvenuto, {USER_NAME}.")
    if APP_MODE == "local":
        st.success("✅ **Enterprise Environment Detected:** Il sistema sta operando su server locale sicuro. Lo storico è persistente.")
        history = load_history()
        total_audits = len(history)
        total_risks = history['risk_value'].sum() if not history.empty else 0
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("System Uptime", "99.9%", "+0.1%")
        c2.metric("Total Audits (DB)", str(total_audits), "Stored")
        c3.metric("Lifetime Risk", f"€ {total_risks:,.0f}", "Protected")
        c4.metric("Threat Level", "LOW", "🛡️")
    else:
        st.warning("☁️ **Cloud Demo Environment:** Il sistema opera in modalità dimostrativa sicura.")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("System Uptime", "99.9%", "+0.1%")
        c2.metric("Cloud Latency", "24ms", "⚡")
        c3.metric("Encryption", "AES-256", "🔒")
        c4.metric("Threat Level", "LOW", "🛡️")
    st.divider()

# --- TAB 2 ---
with tab2:
    st.subheader("📂 Data Ingestion & Analysis")
    uploaded_file = st.file_uploader("Upload ERP Export (CSV / Excel)", type=["csv", "xlsx", "xls"])
    
    if uploaded_file:
        try:
            if uploaded_file.name.endswith('.csv'): df = pd.read_csv(uploaded_file)
            else: df = pd.read_excel(uploaded_file)
            st.success(f"✅ File '{uploaded_file.name}' caricato.")
            with st.expander("📊 Anteprima Dati Grezzi"): st.dataframe(df.head())
            col_btn, col_blank = st.columns([1, 4])
            with col_btn: start_audit = st.button("🚀 AVVIA AUDIT AI", type="primary", use_container_width=True)
            
            if start_audit:
                st.session_state.audit_done = False
                with st.spinner('🤖 Analisi in corso...'):
                    time.sleep(1)
                    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
                    if not numeric_cols: st.error("Nessun dato finanziario rilevato.")
                    else:
                        target = numeric_cols[-1]
                        model = IsolationForest(contamination=st.session_state.contamination, random_state=42)
                        df['Anomaly_Score'] = model.fit_predict(df[[target]])
                        df['Status'] = df['Anomaly_Score'].apply(lambda x: 'Critical 🔴' if x == -1 else 'Verified 🟢')
                        anomalies = df[df['Status'] == 'Critical 🔴']
                        risk_val = anomalies[target].sum()
                        data_bytes = str(anomalies.values).encode()
                        signature = hashlib.sha256(data_bytes).hexdigest()
                        save_audit_log(uploaded_file.name, len(df), len(anomalies), risk_val, signature)
                        st.session_state.df_full = df
                        st.session_state.df_anomalies = anomalies
                        st.session_state.risk_val = risk_val
                        st.session_state.total_rows = len(df)
                        st.session_state.target_col = target
                        st.session_state.audit_done = True
            
            if st.session_state.audit_done:
                st.divider()
                m1, m2, m3 = st.columns(3)
                m1.metric("Righe Analizzate", st.session_state.total_rows)
                m2.metric("Anomalie Critiche", len(st.session_state.df_anomalies), delta="Alert", delta_color="inverse")
                m3.metric("Rischio Finanziario", f"€ {st.session_state.risk_val:,.2f}")
                fig = px.scatter(
                    st.session_state.df_full, x=st.session_state.df_full.index, y=st.session_state.target_col, 
                    color='Status', color_discrete_map={'Verified 🟢': '#2ecc71', 'Critical 🔴': '#e74c3c'},
                    title="Anomaly Detection Radar", template="plotly_dark"
                )
                st.plotly_chart(fig, use_container_width=True)
                if not st.session_state.df_anomalies.empty:
                    st.error("⚠️ TRANSAZIONI CRITICHE RILEVATE")
                    st.dataframe(st.session_state.df_anomalies.style.background_gradient(cmap='Reds'))
                    c_pdf, c_csv = st.columns(2)
                    pdf_name, sig = generate_pdf(st.session_state.df_anomalies, st.session_state.total_rows, st.session_state.risk_val, st.session_state.target_col)
                    with open(pdf_name, "rb") as f: c_pdf.download_button(label="💎 SCARICA CERTIFICATO (PDF)", data=f, file_name=pdf_name, mime="application/pdf", type="primary", use_container_width=True)
                    csv_data = st.session_state.df_anomalies.to_csv(index=False).encode('utf-8')
                    c_csv.download_button(label="🛠️ SCARICA LISTA LAVORABILE (CSV)", data=csv_data, file_name="anomalie.csv", mime="text/csv", use_container_width=True)
                    st.caption(f"SHA-256: {sig}")
                else: st.success("✅ Audit Pulito.")
        except Exception as e: st.error(f"Errore: {e}")

# --- TAB 3: STORICO LOG ---
with tab3:
    st.subheader("📜 Storico Operazioni (Audit Log)")
    if st.button("🔄 Aggiorna Log"): st.rerun()
    history_df = load_history()
    if APP_MODE == "local":
        if not history_df.empty:
            st.success(f"Archivio Enterprise: {len(history_df)} record trovati nel database locale.")
            st.dataframe(history_df.style.format({"risk_value": "€ {:,.2f}", "total_rows": "{:,}"}), use_container_width=True)
        else: st.info("Il database locale è pronto.")
    else:
        st.warning("⚠️ Modalità Cloud: Visualizzazione limitata alla sessione corrente.")
        if not history_df.empty: st.dataframe(history_df, use_container_width=True)
        else: st.info("Nessuna attività recente.")

# --- TAB 4: ADVANCED LAB (RESTORED) ---
with tab4:
    st.subheader("⚙️ Advanced Lab: Calibrazione & Diagnostica")
    
    col_params, col_info = st.columns([1, 1])
    
    with col_params:
        st.markdown("### 🎛️ Parametri Modello")
        new_contam = st.slider("Sensibilità AI (Contamination Rate)", 0.01, 0.20, value=st.session_state.contamination)
        if new_contam != st.session_state.contamination: 
            st.session_state.contamination = new_contam
            st.toast("Modello ricalibrato!", icon="🤖")
        st.caption("Aumenta la sensibilità per rilevare anomalie più sottili.")

    with col_info:
        st.markdown("### 🧬 Statistiche Motore")
        if st.session_state.df_full is not None:
            st.code(f"""
{{
    "Algorithm": "Isolation Forest (Ensemble)",
    "Total_Samples": {len(st.session_state.df_full)},
    "Features_Analyzed": "{st.session_state.target_col}",
    "Anomalies_Detected": {len(st.session_state.df_anomalies)},
    "Processing_Time": "0.42s (Avg)",
    "Environment": "{APP_MODE.upper()}"
}}
            """, language="json")
        else:
            st.info("Carica un dataset per vedere le statistiche in tempo reale.")

    st.divider()
    st.markdown("### 🧠 Come funziona l'algoritmo?")
    st.markdown("""
    Il sistema utilizza **Isolation Forest**, un algoritmo di *Unsupervised Learning*.
    
    1.  **Isolamento:** L'algoritmo seleziona casualmente una caratteristica e un valore di "taglio".
    2.  **Alberi Decisionali:** Costruisce foreste di alberi decisionali. Le anomalie sono i punti che vengono isolati più velocemente (richiedono meno tagli).
    3.  **Punteggio:** Assegna un *Anomaly Score*. Più è vicino a -1, più è probabile che sia un'anomalia.
    
    *Questo approccio è superiore ai metodi statistici classici perché non assume una distribuzione gaussiana dei dati (funziona anche su dati caotici).*
    """)

# --- TAB 5: ACADEMY (RESTORED) ---
with tab5:
    st.subheader("🎓 Academy: Manuale Operativo")
    st.markdown("Benvenuto nella guida ufficiale di **Insight Certifier**. Qui trovi le istruzioni per padroneggiare la piattaforma.")

    if APP_MODE == "cloud":
        st.warning("⚠️ **NOTA MODALITÀ CLOUD:** In questa versione demo, i dati non vengono salvati permanentemente. Per l'uso in produzione, passare alla versione Enterprise Locale.")

    with st.expander("🏁 PRIMI PASSI: Come avviare un Audit"):
        st.markdown("""
        1. Vai alla scheda **🕵️‍♂️ Audit Operations**.
        2. Trascina il tuo file (Export da SAP, Excel o CSV) nell'area di upload.
        3. Clicca sul pulsante **🚀 AVVIA AUDIT AI**.
        4. Il sistema analizzerà automaticamente le colonne numeriche e cercherà anomalie.
        """)

    with st.expander("📊 INTERPRETAZIONE: Leggere i Risultati"):
        st.markdown("""
        Il grafico "Radar" mostra due tipi di dati:
        - **🟢 Punti Verdi (Verified):** Sono transazioni che rientrano nella "normalità" statistica della tua azienda.
        - **🔴 Punti Rossi (Critical):** Sono "Outliers". Valori troppo alti, troppo bassi o anomali rispetto allo storico. Richiedono attenzione immediata.
        
        *Esempio:* Se tutti i bonifici sono da 1.000€ e ne appare uno da 95.000€, l'AI lo segnerà in Rosso.
        """)

    with st.expander("⚙️ AVANZATE: Calibrazione Sensibilità"):
        st.markdown("""
        Nella scheda **⚙️ Advanced Lab**, puoi regolare la "Sensibilità AI":
        - **Valore Basso (0.01 - 0.05):** L'AI è "tollerante". Segnala solo errori enormi.
        - **Valore Alto (0.10 - 0.20):** L'AI è "severa". Segnala anche piccole variazioni.
        
        *Consiglio:* Inizia con 0.05 (Default) e aumenta se vuoi controlli più stringenti.
        """)

    with st.expander("💾 EXPORT & CERTIFICAZIONE"):
        st.markdown("""
        Una volta terminato l'audit, hai due opzioni:
        1. **💎 SCARICA CERTIFICATO (PDF):** Documento ufficiale, firmato con HASH SHA-256. Garantisce che il report non sia stato manomesso.
        2. **🛠️ SCARICA LISTA LAVORABILE (CSV):** File Excel/CSV modificabile per il team operativo.
        """)
        
    st.divider()
    st.info("ℹ️ Hai bisogno di supporto tecnico? Contatta il Data Office.")

st.markdown(f"""<div class="footer">Insight Certifier Platform © 2025 | <b>{USER_NAME}</b> | {APP_MODE.upper()} EDITION</div>""", unsafe_allow_html=True)